### ISSUE TITLE
Conflict with statblock-5e-importer

### ISSUE THREAD

**Issue by Medik-GH** [NoxDied/FVTT-Skill-Customization-5e#2] opened 2022-04-02 17:42 UTC
https://github.com/jbhaywood/5e-statblock-importer/issues/22

**Comment by jbhaywood** [comment] 2022-04-02 22:16
Looking at the line that's failing, which is skl-customization.js, line 27, the problem is that it's not making sure that "skill.bonuses" isn't null. I can fix it on my end by setting that property to zero, but it's kind of a hack. The better fix would be to not make the assumption that it's valid in this module.

If it hasn't been fixed in a few days I'll do a pull request. Since it's a simple fix, I'd rather not go through the trouble of forking and everything if I don't have to. :)

**Comment by Medik-GH** [comment] 2022-04-04 09:56
> Looking at the line that's failing, which is skl-customization.js, line 27, the problem is that it's not making sure that "skill.bonuses" isn't null. I can fix it on my end by setting that property to zero, but it's kind of a hack. The better fix would be to not make the assumption that it's valid in this module.
> 
> If it hasn't been fixed in a few days I'll do a pull request. Since it's a simple fix, I'd rather not go through the trouble of forking and everything if I don't have to. :)

Thanks for your input! I actually found this module was causing my Attack Rolls to fail so this may be a deeper issue. Same error as I posted in your issue. Thanks both for your awesome modules :)

**Comment by NoxDied** [comment] 2022-05-14 15:58
This module is no longer needed as it has been included in the more recent updates of dnd system in foundry. I would advise not using it anymore as I will not be maintaining it and an official alternative has been implemented.
@EddieEldridge
@jbhaywood

**Closed as completed** 2022-05-14 15:59 UTC
